// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFGgumNfDs2h0fQUdn7X6F9KQNiNdVYY',
    appId: '1:1009636275698:web:a29736c221876fde5c276b',
    messagingSenderId: '1009636275698',
    projectId: 'minhasfinancasofc',
    authDomain: 'minhasfinancasofc.firebaseapp.com',
    storageBucket: 'minhasfinancasofc.firebasestorage.app',
    measurementId: 'G-BVM2TMZDMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcGErboOm4fSF7p1AsbM86qK6TMsYmKpM',
    appId: '1:1009636275698:android:743b3324028af14c5c276b',
    messagingSenderId: '1009636275698',
    projectId: 'minhasfinancasofc',
    storageBucket: 'minhasfinancasofc.firebasestorage.app',
  );
}
